apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-compute-service
  namespace: proteinlens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-compute-service
  template:
    metadata:
      labels:
        app: graph-compute-service
    spec:
      containers:
        - name: graph-compute-service
          image: proteinlens/graph-compute-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: password
            - name: SPRING_NEO4J_URI
              value: bolt://neo4j.proteinlens.svc.cluster.local:7687
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.proteinlens.svc.cluster.local:9092
